# -*- coding: utf-8 -*-
"""4.train_compare

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4tvPyHt0hAaBQlYkmyvWsrrahcfVbCW
"""

# !pip install tldextract

from google.colab import files
uploaded = files.upload()

# 라이브러리 불러오기
import pandas as pd
import numpy as np
import re
import math
import ipaddress
from urllib.parse import urlsplit
from collections import Counter
import tldextract

# CSV 데이터 불러오기 및 기본 정보 확인
file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)
df.head()

print("데이터 크기:", df.shape)
print("\n컬럼:")
print(df.columns.tolist())
print("\nLabel 개수:")
print(df['Label'].value_counts())

# URL 및 Label 데이터 전처리
df['URL'] = df['URL'].astype(str).str.strip()
df['Label'] = df['Label'].astype(str).str.strip().str.lower()

print(df['Label'].unique())

# Label 숫자 변환 (악성=0, 정상=1)
df['label'] = df['Label'].map({
    'good': 1,
    'bad': 0
})

print(df['label'].value_counts())
print("라벨 결측값:", df['label'].isnull().sum())

# 결측값 및 라벨 충돌 데이터 제거
df = df.dropna(subset=['URL', 'label'])
label_count = df.groupby('URL')['label'].nunique()
conflict_urls = label_count[label_count > 1].index
print("라벨이 충돌하는 URL:", len(conflict_urls))
df = df[~df['URL'].isin(conflict_urls)]

# 7중복 URL 제거
print("중복 제거 전:", df.shape)

df = df.drop_duplicates(subset='URL')
df = df.reset_index(drop=True)
print("중복 제거 후:", df.shape)

# URL 도메인 분석 및 의심 키워드 설정
extractor = tldextract.TLDExtract(
    suffix_list_urls=None
)

suspicious_keywords = [
    'login',
    'signin',
    'verify',
    'verification',
    'secure',
    'security',
    'account',
    'update',
    'confirm',
    'password',
    'bank',
    'wallet',
    'payment',
    'paypal',
    'bonus',
    'recover',
    'support'
]
# URL 엔트로피 계산 함수
def calculate_entropy(text):
    if not text:
        return 0.0

    counts = Counter(text)
    length = len(text)

    entropy = 0.0

    for count in counts.values():
        probability = count / length
        entropy -= probability * math.log2(probability)

    return entropy

# URL 피처 추출 함수
def extract_features(url):
    url = str(url).strip()

    # http://, https://가 없는 URL도 분석하기 위해 임시로 추가
    parse_url = url

    if '://' not in parse_url:
        parse_url = 'http://' + parse_url

    try:
        parsed = urlsplit(parse_url)
    except:
        parsed = None

    if parsed:
        hostname = parsed.hostname or ''
        path = parsed.path or ''
        query = parsed.query or ''
    else:
        hostname = ''
        path = ''
        query = ''

    # 도메인 분석
    ext = extractor(hostname)

    subdomain = ext.subdomain or ''
    domain = ext.domain or ''
    suffix = ext.suffix or ''

    if suffix:
        root_domain = domain + '.' + suffix
    else:
        root_domain = domain

    # IP 주소 여부
    is_ip = 0

    try:
        ipaddress.ip_address(hostname)
        is_ip = 1
    except:
        is_ip = 0

    # 포트 번호
    try:
        port = parsed.port if parsed and parsed.port else -1
    except:
        port = -1

    # 의심 키워드
    url_lower = url.lower()

    is_filter = int(
        any(keyword in url_lower for keyword in suspicious_keywords)
    )

    # 숫자 개수
    numeric_count = sum(char.isdigit() for char in url)

    # %20, %2F 같은 URL 인코딩
    encoded_list = re.findall(
        r'%[0-9a-fA-F]{2}',
        url
    )

    # 경로 깊이
    path_parts = [
        part
        for part in path.split('/')
        if part
    ]

    # 서브도메인 개수
    if subdomain:
        count_sub_domain = len(
            [x for x in subdomain.split('.') if x]
        )
    else:
        count_sub_domain = 0

    features = {
        'len_url': len(url),
        'len_sub_domain': len(subdomain),
        'len_root_domain': len(root_domain),
        'len_suffix': len(suffix),
        'len_encoding': len(encoded_list) * 3,
        'len_query': len(query),
        'count_sub_domain': count_sub_domain,
        'count_file_path': len(path_parts),
        'count_special_char': sum(
            not char.isalnum()
            for char in url
        ),
        'count_url_dots': url.count('.'),
        'is_ip': is_ip,
        'is_filter': is_filter,
        'num_port': port,
        'value_entropy_url': calculate_entropy(url)
    }

    return features

# 피처 추출 함수 테스트
test_url = df['URL'].iloc[0]

print("URL:", test_url)
print(extract_features(test_url))

# 전체 URL에서 피처 추출
from tqdm.auto import tqdm
tqdm.pandas()

feature_list = df['URL'].progress_apply(
    extract_features
)

features_df = pd.DataFrame(
    feature_list.tolist()
)

features_df.head()

print(features_df.shape)
print(features_df.columns.tolist())

# 학습용 데이터 생성 및 CSV 저장
train_urls = features_df.copy()
train_urls['label'] = df['label'].values
train_urls.head()

train_urls.to_csv(
    'train_urls.csv',
    index=False
)
print("train_urls.csv 생성 완료")

# 입력 데이터(X)와 정답 데이터(y) 분리
X = train_urls.drop(
    'label',
    axis=1
)

y = train_urls['label']

print("X:", X.shape)
print("y:", y.shape)

print("\n라벨 개수:")
print(y.value_counts())

# 학습 데이터와 테스트 데이터 분리
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

# Random Forest 기본 모델 학습
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(
    X_train,
    y_train
)

y_pred = rf_model.predict(
    X_test
)
# Random Forest 기본 모델 성능 평가
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    pos_label=0
)

recall = recall_score(
    y_test,
    y_pred,
    pos_label=0
)

f1 = f1_score(
    y_test,
    y_pred,
    pos_label=0
)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-Score :", f1)

print(
    confusion_matrix(
        y_test,
        y_pred,
        labels=[0, 1]
    )
)

print(
    classification_report(
        y_test,
        y_pred,
        labels=[0, 1],
        target_names=[
            '악성',
            '정상'
        ]
    )
)

#  Random Forest 하이퍼파라미터 튜닝
rf_model = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

y_pred_tuned = rf_model.predict(X_test)

# Random Forest 튜닝 모델 성능 평가
print(
    classification_report(
        y_test,
        y_pred_tuned,
        labels=[0, 1],
        target_names=['악성', '정상']
    )
)

# XGBoost 1차 튜닝 모델 학습
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=8,
    learning_rate=0.05,
    min_child_weight=2,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    random_state=42,
    n_jobs=-1,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)

from sklearn.metrics import classification_report

# XGBoost 1차 튜닝 모델 성능 평가
print("===== XGBoost 튜닝 결과 =====")
print(
    classification_report(
        y_test,
        xgb_pred,
        labels=[0, 1],
        target_names=['악성', '정상']
    )
)

#  클래스 불균형 보정을 위한 가중치 계산
from sklearn.utils.class_weight import compute_sample_weight
from xgboost import XGBClassifier

# 클래스 불균형 보정
sample_weights = compute_sample_weight(
    class_weight='balanced',
    y=y_train
)

# XGBoost 2차 튜닝
xgb_model_tuned2 = XGBClassifier(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    min_child_weight=1,
    subsample=0.9,
    colsample_bytree=0.9,
    gamma=0,
    random_state=42,
    n_jobs=-1,
    eval_metric='logloss'
)

xgb_model_tuned2.fit(
    X_train,
    y_train,
    sample_weight=sample_weights
)

xgb_pred_tuned2 = xgb_model_tuned2.predict(X_test)

from sklearn.metrics import classification_report

#  XGBoost 2차 튜닝 모델 성능 평가
print("===== XGBoost 2차튜닝 결과 =====")

print(
    classification_report(
        y_test,
        xgb_pred_tuned2,
        labels=[0, 1],
        target_names=['악성', '정상']
    )
)