# -*- coding: utf-8 -*-
"""Random Forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4tvPyHt0hAaBQlYkmyvWsrrahcfVbCW
"""

# !pip install tldextract

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import re
import math
import ipaddress
from urllib.parse import urlsplit
from collections import Counter
import tldextract

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)
df.head()

print("데이터 크기:", df.shape)
print("\n컬럼:")
print(df.columns.tolist())
print("\nLabel 개수:")
print(df['Label'].value_counts())

df['URL'] = df['URL'].astype(str).str.strip()
df['Label'] = df['Label'].astype(str).str.strip().str.lower()

print(df['Label'].unique())

df['label'] = df['Label'].map({
    'good': 1,
    'bad': 0
})

print(df['label'].value_counts())
print("라벨 결측값:", df['label'].isnull().sum())

df = df.dropna(subset=['URL', 'label'])
label_count = df.groupby('URL')['label'].nunique()
conflict_urls = label_count[label_count > 1].index

print("라벨이 충돌하는 URL:", len(conflict_urls))

df = df[~df['URL'].isin(conflict_urls)]
print(X.select_dtypes(include='object').columns.tolist())
print("중복 제거 전:", df.shape)

df = df.drop_duplicates(subset='URL')
df = df.reset_index(drop=True)

print("중복 제거 후:", df.shape)

extractor = tldextract.TLDExtract(
    suffix_list_urls=None
)

suspicious_keywords = [
    'login',
    'signin',
    'verify',
    'verification',
    'secure',
    'security',
    'account',
    'update',
    'confirm',
    'password',
    'bank',
    'wallet',
    'payment',
    'paypal',
    'bonus',
    'recover',
    'support'
]

def calculate_entropy(text):
    if not text:
        return 0.0

    counts = Counter(text)
    length = len(text)

    entropy = 0.0

    for count in counts.values():
        probability = count / length
        entropy -= probability * math.log2(probability)

    return entropy

def extract_features(url):

    url = str(url).strip()

    # http://, https://가 없는 URL도 분석하기 위해 임시로 추가
    parse_url = url

    if '://' not in parse_url:
        parse_url = 'http://' + parse_url

    try:
        parsed = urlsplit(parse_url)
    except:
        parsed = None

    if parsed:
        hostname = parsed.hostname or ''
        path = parsed.path or ''
        query = parsed.query or ''
    else:
        hostname = ''
        path = ''
        query = ''

    # 도메인 분석
    ext = extractor(hostname)

    subdomain = ext.subdomain or ''
    domain = ext.domain or ''
    suffix = ext.suffix or ''

    if suffix:
        root_domain = domain + '.' + suffix
    else:
        root_domain = domain

    # IP 주소 여부
    is_ip = 0

    try:
        ipaddress.ip_address(hostname)
        is_ip = 1
    except:
        is_ip = 0

    # 포트 번호
    try:
        port = parsed.port if parsed and parsed.port else -1
    except:
        port = -1

    # 의심 키워드
    url_lower = url.lower()

    is_filter = int(
        any(keyword in url_lower for keyword in suspicious_keywords)
    )

    # 숫자 개수
    numeric_count = sum(char.isdigit() for char in url)

    # %20, %2F 같은 URL 인코딩
    encoded_list = re.findall(
        r'%[0-9a-fA-F]{2}',
        url
    )

    # 경로 깊이
    path_parts = [
        part
        for part in path.split('/')
        if part
    ]

    # 서브도메인 개수
    if subdomain:
        count_sub_domain = len(
            [x for x in subdomain.split('.') if x]
        )
    else:
        count_sub_domain = 0

    features = {
        'len_url': len(url),
        'len_sub_doain': len(subdomain),
        'len_root_domain': len(root_domain),
        'len_suffix': len(suffix),
        'len_encoding': len(encoded_list) * 3,
        'len_query': len(query),
        'count_sub_domain': count_sub_domain,
        'count_file_path': len(path_parts),
        'count_special_char': sum(
            not char.isalnum()
            for char in url
        ),

        'count_url_dots': url.count('.'),
        'is_ip': is_ip,
        'is_filter': is_filter,
        'num_port': port,
        'ratio_alpha_numeric': ratio_alpha_numeric,
        'value_entropy_url': calculate_entropy(url)
    }

    return features

test_url = df['URL'].iloc[0]

print("URL:", test_url)
print(extract_features(test_url))

from tqdm.auto import tqdm

tqdm.pandas()

feature_list = df['URL'].progress_apply(
    extract_features
)

features_df = pd.DataFrame(
    feature_list.tolist()
)

features_df.head()

print(features_df.shape)
print(features_df.columns.tolist())

train_urls = features_df.copy()
train_urls['label'] = df['label'].values
train_urls.head()
train_urls.to_csv(
    'train_urls.csv',
    index=False
)

print("train_urls.csv 생성 완료")

X = train_urls.drop(
    'label',
    axis=1
)

y = train_urls['label']

print("X:", X.shape)
print("y:", y.shape)

print("\n라벨 개수:")
print(y.value_counts())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(
    X_train,
    y_train
)

y_pred = rf_model.predict(
    X_test
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    pos_label=0
)

recall = recall_score(
    y_test,
    y_pred,
    pos_label=0
)

f1 = f1_score(
    y_test,
    y_pred,
    pos_label=0
)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-Score :", f1)

print(
    confusion_matrix(
        y_test,
        y_pred,
        labels=[0, 1]
    )
)

print(
    classification_report(
        y_test,
        y_pred,
        labels=[0, 1],
        target_names=[
            '악성',
            '정상'
        ]
    )
)

"""튜닝"""

rf_model = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

y_pred_tuned = rf_model.predict(X_test)

print(
    classification_report(
        y_test,
        y_pred_tuned,
        labels=[0, 1],
        target_names=['악성', '정상']
    )
)
